# tasks file for jenkins
---
- name: Install yum
  yum:
        name:
          - wget
          - "{{java.VERSION}}"

- name: Download jenkins.repo
  get_url:
        url: "{{jenkins.repo_URL}}"
        dest: /etc/yum.repos.d/jenkins.repo

- name: Import Jenkins Key
  rpm_key:
        state: present
        key: "{{jenkins.gpg_key}}"

- name: Install Jenkins
  yum:
        name: jenkins
        state: present

#- name: Start & Enable Jenkins
#  service:
#        name: jenkins
#        state: started
#        enabled: true

- name: Stop Jenkins
  systemd:
        name: jenkins
        state: stopped

- name: creating directory for groovy scripts
  file:
    path: /var/lib/jenkins/init.groovy.d/
    mode: 0755
    owner: jenkins
    group: jenkins
    state: directory

- name: opying file with owner and permissions
  copy:
    src: ~/jenkins-playbook/roles/jenkins/files/security.groovy
    dest: /var/lib/jenkins/init.groovy.d/security.groovy
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Change Jenkins JAVA options
  lineinfile: 
    dest=/etc/sysconfig/jenkins
    regexp=^JENKINS_JAVA_OPTIONS=
    line=JENKINS_JAVA_OPTIONS="{{ jenkins.JAVA_OPTIONS }}"
  become: true

- name: Start & Enable Jenkins
  systemd:
        name: jenkins
        state: started

- name: Sleep for 30 seconds and continue with play
  wait_for: timeout=30

#- name: Get init password Jenkins
#  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
#  changed_when: false
#  register: result

#- name: Print init password Jenkins
#  debug:
#        var: result.stdout
